#
# Release configuration for current measurement.
# Apply with:
#   -DEXTRA_CONF_FILE=prj_release.conf
#

# Do not initialize serial, console, or UART logging.
CONFIG_LOG=n
CONFIG_LOG_BACKEND_UART_ASYNC=n
CONFIG_UART_ASYNC_API=n
CONFIG_SERIAL=n
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n
CONFIG_LOG_PRINTK=n
CONFIG_NCS_BOOT_BANNER=n
CONFIG_BOOT_BANNER=n
CONFIG_EARLY_CONSOLE=n
CONFIG_PRINTK=n
CONFIG_UART_20_ASYNC=n
