#
# Idle baseline image.
# The application returns immediately and PDM/DMIC are disabled.
#

CONFIG_PDM_DEMO_ENABLE=n
CONFIG_AUDIO_DMIC=n
CONFIG_AUDIO_DMIC_NRFX_PDM=n
CONFIG_NRFX_PDM=n

CONFIG_LOG=n
CONFIG_LOG_BACKEND_UART_ASYNC=n
CONFIG_UART_ASYNC_API=n
CONFIG_SERIAL=n
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n
CONFIG_LOG_PRINTK=n
CONFIG_NCS_BOOT_BANNER=n
CONFIG_BOOT_BANNER=n
CONFIG_EARLY_CONSOLE=n
CONFIG_PRINTK=n
CONFIG_UART_20_ASYNC=n
